### ISSUE TITLE
Secure instance

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/demo-inveniordm#1]

**Comment by ppanero** [comment]
Added `SECRET_KEY change to the Helm chart (was manually until now) https://github.com/inveniosoftware/helm-invenio/pull/12. Allowed hosts are already pre-configure in the chart and `WSGI_PROXIES` is correct with the default value. Ensuring records creation was disabled was treated here https://github.com/inveniosoftware/demo-inveniordm/issues/3
