### ISSUE TITLE
Demo instance update (October release)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/demo-inveniordm#27]
Update the demo instance with the latest October release.

**Comment by ppanero** [comment]
https://inveniordm-qa.web.cern.ch and https://inveniordm.web.cern.ch both have been migrated. Tested:

- add demo data and view its landing page
- created a draft and publish it (only one save ;) ). search it in the search page.
- created a draft, leave it as draft, view it in uploads page and access it again as edit

Above cases working
